# Nushell environment — sourced before config.nu

# PATH (chezmoi-managed tool locations)
$env.PATH = ($env.PATH | split row (char esep) | prepend [
    ($env.HOME | path join ".local" "bin")    # local binaries (chezmoi installs here on Linux; uv tools symlink here)
    ($env.HOME | path join ".cargo" "bin")    # rust / cargo tools
    ($env.HOME | path join "go"     "bin")    # go tools (gopls, etc.)
    ($env.HOME | path join ".bun"   "bin")    # bun global packages
] | uniq)

# Editor
$env.EDITOR = "hx"
$env.VISUAL = "hx"

# True color (24-bit) — Linux 環境で Helix のテーマカラーが 256 色に丸められないように明示
$env.COLORTERM = "truecolor"

# Starship prompt is auto-loaded from $nu.data-dir/vendor/autoload/starship.nu
# (generated by .chezmoiscripts/run_onchange_02_setup-nushell.sh.tmpl)
